'use client';
import React, { useState } from 'react';
import { Eraser, Download, Copy, Check, FileCode } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { formatFileSize, calcReductionPct, downloadBlob, copyToClipboard } from '@/lib/utils';
import { useToast } from '@/components/ui/ToastProvider';

function cleanSvgMarkup(svg: string): string {
  return svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<\?xml[\s\S]*?\?>/gi, '')
    .replace(/<!DOCTYPE[\s\S]*?>/gi, '')
    .replace(/<metadata[\s\S]*?<\/metadata>/gi, '')
    .replace(/<desc[\s\S]*?<\/desc>/gi, '')
    .replace(/<title[\s\S]*?<\/title>/gi, '')
    .replace(/\s+xmlns:(inkscape|sodipodi|sketch|i|adobe)="[^"]*"/gi, '')
    .replace(/\s+(inkscape|sodipodi|sketch):[a-zA-Z0-9_-]+="[^"]*"/gi, '')
    .replace(/\s+id="(?:layer|g|path)[0-9]+"/gi, '')
    .replace(/\s+version="1\.[01]"/gi, '')
    .replace(/\s+xml:space="preserve"/gi, '')
    .replace(/>\s+</g, '><')
    .trim();
}

export default function SvgCleanerTool() {
  const [inputSvg, setInputSvg] = useState('');
  const [cleanedSvg, setCleanedSvg] = useState('');
  const [copied, setCopied] = useState(false);
  const toast = useToast();

  const handleClean = (text = inputSvg) => {
    if (!text.trim()) {
      setCleanedSvg('');
      return;
    }
    const res = cleanSvgMarkup(text);
    setCleanedSvg(res);
    toast.success('Cleaned SVG bloat!');
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = evt => {
      const content = evt.target?.result as string;
      setInputSvg(content);
      handleClean(content);
    };
    reader.readAsText(file);
  };

  const originalSize = new TextEncoder().encode(inputSvg).length;
  const cleanedSize = new TextEncoder().encode(cleanedSvg).length;

  const handleCopy = async () => {
    if (!cleanedSvg) return;
    await copyToClipboard(cleanedSvg);
    setCopied(true);
    toast.success('Cleaned SVG copied');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!cleanedSvg) return;
    const blob = new Blob([cleanedSvg], { type: 'image/svg+xml;charset=utf-8' });
    downloadBlob(blob, 'cleaned.svg');
  };

  const loadSample = () => {
    const sample = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by Adobe Illustrator 25.0 -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="100" height="100" version="1.1">
  <metadata>
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <cc:Work rdf:about="" />
    </rdf:RDF>
  </metadata>
  <circle cx="50" cy="50" r="40" stroke="#6366F1" stroke-width="4" fill="#E0E7FF" id="path1234" />
</svg>`;
    setInputSvg(sample);
    handleClean(sample);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {/* Control Bar */}
      <div className="card" style={{ padding: '12px 16px', display: 'flex', flexWrap: 'wrap', gap: 10, alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
          <Button onClick={() => handleClean()}>Clean SVG</Button>
          <Button variant="ghost" size="sm" onClick={loadSample}>Sample SVG</Button>
          <label>
            <input type="file" accept=".svg,image/svg+xml" onChange={handleFileUpload} style={{ display: 'none' }} />
            <span className="btn-secondary" style={{ display: 'inline-flex', alignItems: 'center', height: 32, padding: '0 12px', fontSize: 13, cursor: 'pointer' }}>
              Upload SVG
            </span>
          </label>
        </div>

        <div style={{ display: 'flex', gap: 8 }}>
          <Button variant="secondary" size="sm" onClick={handleCopy} disabled={!cleanedSvg} icon={copied ? <Check size={14} /> : <Copy size={14} />}>
            {copied ? 'Copied' : 'Copy'}
          </Button>
          <Button variant="secondary" size="sm" onClick={handleDownload} disabled={!cleanedSvg} icon={<Download size={14} />}>
            Download .svg
          </Button>
        </div>
      </div>

      {cleanedSvg && (
        <div style={{
          padding: '10px 14px', borderRadius: 'var(--radius-md)', background: 'var(--color-surface2)',
          display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: 13,
        }}>
          <span>Original: <strong>{formatFileSize(originalSize)}</strong> &rarr; Cleaned: <strong>{formatFileSize(cleanedSize)}</strong></span>
          <span style={{ color: 'var(--color-success)', fontWeight: 600 }}>
            Saved {calcReductionPct(originalSize, cleanedSize)}% bloat
          </span>
        </div>
      )}

      {/* Editor & Preview */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 16 }}>
        <div className="card" style={{ display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
          <div style={{ padding: '8px 14px', borderBottom: '1px solid var(--color-border)', fontSize: 12, fontWeight: 700, color: 'var(--color-muted)' }}>
            INPUT SVG
          </div>
          <textarea
            value={inputSvg}
            onChange={e => {
              setInputSvg(e.target.value);
              handleClean(e.target.value);
            }}
            placeholder="Paste SVG code here or upload an SVG file above..."
            style={{
              width: '100%', height: 360, padding: 14,
              background: 'transparent', border: 'none', outline: 'none',
              color: 'var(--color-text)', fontFamily: 'var(--font-mono)', fontSize: 13,
              resize: 'none', boxSizing: 'border-box', lineHeight: 1.5,
            }}
          />
        </div>

        <div className="card" style={{ display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
          <div style={{ padding: '8px 14px', borderBottom: '1px solid var(--color-border)', fontSize: 12, fontWeight: 700, color: 'var(--color-muted)', display: 'flex', justifyContent: 'space-between' }}>
            <span>CLEANED SVG PREVIEW</span>
            {cleanedSvg && <span>{cleanedSize} bytes</span>}
          </div>
          <div style={{ height: 180, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16, borderBottom: '1px solid var(--color-border)', background: 'var(--color-surface2)' }}>
            {cleanedSvg ? (
              <div dangerouslySetInnerHTML={{ __html: cleanedSvg }} style={{ maxWidth: '100%', maxHeight: '100%' }} />
            ) : (
              <span style={{ color: 'var(--color-faint)', fontSize: 13 }}>Preview will appear here</span>
            )}
          </div>
          <textarea
            readOnly
            value={cleanedSvg}
            placeholder="Cleaned SVG markup..."
            style={{
              width: '100%', height: 180, padding: 14,
              background: 'transparent', border: 'none', outline: 'none',
              color: 'var(--color-text)', fontFamily: 'var(--font-mono)', fontSize: 12,
              resize: 'none', boxSizing: 'border-box', lineHeight: 1.5,
            }}
          />
        </div>
      </div>
    </div>
  );
}
