import type { Tool, Category } from './types';

const A = 'active' as const;
const S = 'stub'   as const;
const c = 'client' as const;
const n = 'none'   as const;

export const TOOLS: Tool[] = [
  // ── Images ──────────────────────────────────────────────────────────────
  { name:'Images to Text', slug:'image-to-text', category:'Images', description:'Extract text from any image line after line using in-browser OCR.', longDescription:'Fetch and recognize text from screenshots, documents, receipts, photos, and book pages. Preserves exact line-by-line formatting with instant copying and export — 100% in your browser.', keywords:['images to text','image to text','ocr','extract text from image','photo to text','read text from picture','scan text'], icon:'ScanText', formats:{in:['JPG','PNG','WebP','BMP','GIF'],out:['TXT','JSON']}, related:['pdf-to-text','image-compressor','background-remover'], status:A, processing:c, dataStorage:n },
  { name:'Image Compressor', slug:'image-compressor', category:'Images', description:'Compress JPEG, PNG, WebP, GIF, AVIF, BMP, TIFF, ICO and SVG without visible quality loss.', longDescription:'Near-lossless compression for all major image formats entirely in your browser. Batch-process multiple images and download a ZIP.', keywords:['compress image','reduce image size','jpg compressor','png compressor','webp compress','image optimizer','squoosh','tinypng'], icon:'ImageDown', formats:{in:['JPG','PNG','WebP','GIF','AVIF','BMP','TIFF','ICO','SVG'],out:['JPG','PNG','WebP','BMP','TIFF','ICO','SVG']}, related:['image-resizer','image-converter','jpg-to-webp','image-metadata-remover'], status:A, processing:c, dataStorage:n },
  { name:'Image Resizer', slug:'image-resizer', category:'Images', description:'Resize images to any dimension while maintaining aspect ratio.', keywords:['resize image','scale image','image dimensions','make image smaller'], icon:'Scaling', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-compressor','image-cropper','batch-image-resizer'], status:A, processing:c, dataStorage:n },
  { name:'Background Remover', slug:'background-remover', category:'Images', description:'Instantly remove image backgrounds using AI — runs entirely in your browser, no uploads.', longDescription:'Use a lightweight on-device AI model to remove backgrounds from photos, product images, and portraits. Choose transparent, white, black, or a custom color as the new background. Works 100% offline — your images never leave your device.', keywords:['remove background','background remover','transparent background','no background','ai background remove','cut out background','remove bg'], icon:'Scissors', isBeta:true, formats:{in:['JPG','PNG','WebP'],out:['PNG']}, related:['image-compressor','image-watermark','image-blur'], status:A, processing:c, dataStorage:n },
  { name:'Image Cropper', slug:'image-cropper', category:'Images', description:'Crop images with a visual selection tool. Export any region.', keywords:['crop image','trim image','cut image'], icon:'Crop', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-resizer','image-rotator'], status:A, processing:c, dataStorage:n },
  { name:'Image Rotator', slug:'image-rotator', category:'Images', description:'Rotate images 90°, 180°, or any custom angle.', keywords:['rotate image','flip image','turn image'], icon:'RotateCw', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-flipper','image-cropper'], status:A, processing:c, dataStorage:n },
  { name:'Image Flipper', slug:'image-flipper', category:'Images', description:'Flip images horizontally or vertically.', keywords:['flip image','mirror image','horizontal flip','vertical flip'], icon:'FlipHorizontal', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-rotator','image-cropper'], status:A, processing:c, dataStorage:n },
  { name:'Image Converter', slug:'image-converter', category:'Images', description:'Convert images between JPG, PNG, WebP, AVIF and other formats.', keywords:['convert image','image format converter','jpg to png','png to webp'], icon:'RefreshCw', formats:{in:['JPG','PNG','WebP','AVIF','BMP','GIF'],out:['JPG','PNG','WebP','AVIF']}, related:['jpg-to-webp','png-to-jpg','jpg-to-png'], status:A, processing:c, dataStorage:n },
  { name:'Image Quality Changer', slug:'image-quality', category:'Images', description:'Adjust JPEG/WebP quality to fine-tune the size/quality balance.', keywords:['image quality','jpeg quality','webp quality','compress level'], icon:'SlidersHorizontal', formats:{in:['JPG','WebP'],out:['JPG','WebP']}, related:['image-compressor','image-converter'], status:A, processing:c, dataStorage:n },
  { name:'Image Metadata Viewer', slug:'image-metadata-viewer', category:'Images', description:'View EXIF, IPTC, and XMP metadata embedded in your images.', keywords:['exif viewer','image metadata','photo info','gps exif'], icon:'Info', formats:{in:['JPG','PNG','WebP','TIFF']}, related:['image-metadata-remover','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'Image Metadata Remover', slug:'image-metadata-remover', category:'Images', description:'Strip EXIF and all metadata from images to protect your privacy.', keywords:['remove exif','strip metadata','privacy image','remove gps'], icon:'EyeOff', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-metadata-viewer','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'Image DPI Calculator', slug:'image-dpi', category:'Images', description:'Calculate the DPI / PPI of an image and convert between sizes.', keywords:['dpi calculator','ppi image','print resolution','dots per inch'], icon:'Gauge', formats:{in:['JPG','PNG','WebP']}, related:['image-resizer','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'Image Color Picker', slug:'image-color-picker', category:'Images', description:'Pick any colour from an image — get HEX, RGB, and HSL values.', keywords:['color picker','eyedropper','pick color from image','hex from image'], icon:'Pipette', formats:{in:['JPG','PNG','WebP']}, related:['hex-to-rgb','rgb-to-hex','color-palette'], status:A, processing:c, dataStorage:n },
  { name:'Image Blur', slug:'image-blur', category:'Images', description:'Apply Gaussian blur to images or specific regions.', keywords:['blur image','gaussian blur','pixelate image'], icon:'Blend', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-watermark','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'Image Watermark', slug:'image-watermark', category:'Images', description:'Add text or image watermarks to your photos.', keywords:['watermark image','add watermark','copyright image'], icon:'Stamp', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-blur','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'Image Grayscale', slug:'image-grayscale', category:'Images', description:'Convert colour images to grayscale or black and white.', keywords:['grayscale image','black and white','desaturate image'], icon:'Contrast', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-compressor','image-quality'], status:A, processing:c, dataStorage:n },
  { name:'JPG → PNG', slug:'jpg-to-png', category:'Images', description:'Convert JPEG images to lossless PNG format.', keywords:['jpg to png','jpeg to png','convert jpg png'], icon:'ArrowRight', formats:{in:['JPG'],out:['PNG']}, related:['png-to-jpg','jpg-to-webp','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'PNG → JPG', slug:'png-to-jpg', category:'Images', description:'Convert PNG images to JPEG with quality control.', keywords:['png to jpg','png to jpeg','convert png jpg'], icon:'ArrowRight', formats:{in:['PNG'],out:['JPG']}, related:['jpg-to-png','png-to-webp'], status:A, processing:c, dataStorage:n },
  { name:'JPG → WebP', slug:'jpg-to-webp', category:'Images', description:'Convert JPEG to WebP for smaller web-optimised files.', keywords:['jpg to webp','jpeg to webp','convert webp'], icon:'ArrowRight', formats:{in:['JPG'],out:['WebP']}, related:['png-to-webp','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'PNG → WebP', slug:'png-to-webp', category:'Images', description:'Convert PNG images to the modern WebP format.', keywords:['png to webp','convert webp','png webp'], icon:'ArrowRight', formats:{in:['PNG'],out:['WebP']}, related:['jpg-to-webp','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'WebP → JPG', slug:'webp-to-jpg', category:'Images', description:'Convert WebP images back to universal JPEG format.', keywords:['webp to jpg','webp to jpeg','convert webp jpg'], icon:'ArrowRight', formats:{in:['WebP'],out:['JPG']}, related:['webp-to-png','jpg-to-webp'], status:A, processing:c, dataStorage:n },
  { name:'WebP → PNG', slug:'webp-to-png', category:'Images', description:'Convert WebP images to PNG format.', keywords:['webp to png','convert webp png'], icon:'ArrowRight', formats:{in:['WebP'],out:['PNG']}, related:['webp-to-jpg','png-to-webp'], status:A, processing:c, dataStorage:n },
  { name:'WebP → AVIF', slug:'webp-to-avif', category:'Images', description:'Convert WebP images to ultra-compressed AVIF format.', keywords:['webp to avif','convert webp avif'], icon:'ArrowRight', formats:{in:['WebP'],out:['AVIF']}, related:['avif-to-jpg','avif-to-png'], status:A, processing:c, dataStorage:n },
  { name:'AVIF → JPG', slug:'avif-to-jpg', category:'Images', description:'Convert AVIF images to universally supported JPEG format.', keywords:['avif to jpg','convert avif jpg'], icon:'ArrowRight', formats:{in:['AVIF'],out:['JPG']}, related:['avif-to-png','webp-to-avif'], status:A, processing:c, dataStorage:n },
  { name:'AVIF → PNG', slug:'avif-to-png', category:'Images', description:'Convert AVIF images to lossless PNG format.', keywords:['avif to png','convert avif png'], icon:'ArrowRight', formats:{in:['AVIF'],out:['PNG']}, related:['avif-to-jpg','webp-to-avif'], status:A, processing:c, dataStorage:n },
  { name:'HEIC → JPG', slug:'heic-to-jpg', category:'Images', description:'Convert Apple HEIC photos to standard JPEG.', keywords:['heic to jpg','convert heic jpeg','iphone photo to jpg'], icon:'ArrowRight', formats:{in:['HEIC'],out:['JPG']}, related:['heic-to-png','jpg-to-png'], status:A, processing:c, dataStorage:n },
  { name:'HEIC → PNG', slug:'heic-to-png', category:'Images', description:'Convert Apple HEIC photos to lossless PNG.', keywords:['heic to png','convert heic png'], icon:'ArrowRight', formats:{in:['HEIC'],out:['PNG']}, related:['heic-to-jpg','png-to-jpg'], status:A, processing:c, dataStorage:n },
  { name:'GIF → JPG', slug:'gif-to-jpg', category:'Images', description:'Extract and convert GIF frames to JPEG images.', keywords:['gif to jpg','gif to jpeg','convert gif'], icon:'ArrowRight', formats:{in:['GIF'],out:['JPG']}, related:['gif-to-png','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'GIF → PNG', slug:'gif-to-png', category:'Images', description:'Convert GIF images or extract frames to PNG.', keywords:['gif to png','convert gif png'], icon:'ArrowRight', formats:{in:['GIF'],out:['PNG']}, related:['gif-to-jpg','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'Batch Image Compressor', slug:'batch-image-compressor', category:'Images', description:'Compress dozens of images at once and download as a ZIP.', keywords:['batch compress images','bulk image compressor','multiple images'], icon:'Package', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-compressor','batch-image-resizer'], status:A, processing:c, dataStorage:n },
  { name:'Batch Image Resizer', slug:'batch-image-resizer', category:'Images', description:'Resize multiple images to the same dimensions in one go.', keywords:['batch resize','bulk resize images','multiple images resize'], icon:'LayoutGrid', formats:{in:['JPG','PNG','WebP'],out:['JPG','PNG','WebP']}, related:['image-resizer','batch-image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'Batch Image Converter', slug:'batch-image-converter', category:'Images', description:'Convert multiple images between formats and download as a ZIP.', keywords:['batch convert images','bulk image converter','batch webp png'], icon:'RefreshCw', formats:{in:['JPG','PNG','WebP','BMP','GIF'],out:['JPG','PNG','WebP','BMP']}, related:['batch-image-compressor','image-converter'], status:A, processing:c, dataStorage:n },
  { name:'SVG Cleaner', slug:'svg-cleaner', category:'Images', description:'Remove SVG bloat: comments, metadata, and redundant attributes.', keywords:['svg cleaner','optimize svg','clean svg','svgo'], icon:'Eraser', formats:{in:['SVG'],out:['SVG']}, related:['svg-optimizer','svg-to-png'], status:A, processing:c, dataStorage:n },
  { name:'SVG Optimizer', slug:'svg-optimizer', category:'Images', description:'Minify and optimize SVG path data and attributes.', keywords:['svg optimizer','svgo','minify svg','compress svg'], icon:'Minimize2', formats:{in:['SVG'],out:['SVG']}, related:['svg-cleaner','svg-preview'], status:A, processing:c, dataStorage:n },
  { name:'SVG → PNG', slug:'svg-to-png', category:'Images', description:'Render SVG files to high-resolution PNG images.', keywords:['svg to png','convert svg png','rasterize svg'], icon:'ArrowRight', formats:{in:['SVG'],out:['PNG']}, related:['svg-cleaner','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'SVG → JPG', slug:'svg-to-jpg', category:'Images', description:'Render SVG files to JPEG images with background color.', keywords:['svg to jpg','convert svg jpg'], icon:'ArrowRight', formats:{in:['SVG'],out:['JPG']}, related:['svg-to-png','svg-cleaner'], status:A, processing:c, dataStorage:n },
  { name:'SVG Preview', slug:'svg-preview', category:'Images', description:'Preview and inspect SVG files with zoom and pan.', keywords:['preview svg','view svg','svg viewer'], icon:'Eye', related:['svg-cleaner','svg-optimizer'], status:A, processing:c, dataStorage:n },

  // ── PDF ─────────────────────────────────────────────────────────────────
  { name:'PDF Compressor', slug:'pdf-compressor', category:'PDF', description:'Reduce PDF file size by compressing embedded images and streams.', longDescription:'Compress PDF files by downsampling embedded images and removing redundant data — all in your browser using PDF-lib. No uploads to any server.', keywords:['compress pdf','reduce pdf size','pdf optimizer','pdf compressor','smaller pdf'], icon:'FileDown', formats:{in:['PDF'],out:['PDF']}, related:['pdf-merger','pdf-splitter','pdf-to-jpg'], status:A, processing:c, dataStorage:n },
  { name:'PDF Merger', slug:'pdf-merger', category:'PDF', description:'Merge multiple PDF files into a single document.', keywords:['merge pdf','combine pdf','join pdf files'], icon:'FilePlus', formats:{in:['PDF'],out:['PDF']}, related:['pdf-splitter','pdf-organizer','pdf-compressor'], status:A, processing:c, dataStorage:n },
  { name:'PDF Splitter', slug:'pdf-splitter', category:'PDF', description:'Split a PDF into individual pages or page ranges.', keywords:['split pdf','extract pages','divide pdf'], icon:'Scissors', formats:{in:['PDF'],out:['PDF']}, related:['pdf-merger','pdf-page-extractor'], status:A, processing:c, dataStorage:n },
  { name:'PDF Rotator', slug:'pdf-rotator', category:'PDF', description:'Rotate PDF pages 90°, 180°, or 270°.', keywords:['rotate pdf','turn pdf pages','fix pdf orientation'], icon:'RotateCw', formats:{in:['PDF'],out:['PDF']}, related:['pdf-organizer','pdf-merger'], status:A, processing:c, dataStorage:n },
  { name:'PDF Page Extractor', slug:'pdf-page-extractor', category:'PDF', description:'Extract specific pages or page ranges from a PDF.', keywords:['extract pdf pages','remove pages pdf','pdf page extractor'], icon:'FileMinus', formats:{in:['PDF'],out:['PDF']}, related:['pdf-splitter','pdf-page-deleter'], status:A, processing:c, dataStorage:n },
  { name:'PDF Page Deleter', slug:'pdf-page-deleter', category:'PDF', description:'Delete unwanted pages from a PDF file.', keywords:['delete pdf pages','remove page pdf'], icon:'Trash2', formats:{in:['PDF'],out:['PDF']}, related:['pdf-page-extractor','pdf-splitter'], status:A, processing:c, dataStorage:n },
  { name:'PDF → JPG', slug:'pdf-to-jpg', category:'PDF', description:'Convert PDF pages to high-quality JPG images.', keywords:['pdf to jpg','pdf to image','convert pdf jpg'], icon:'ArrowRight', formats:{in:['PDF'],out:['JPG']}, related:['pdf-to-png','jpg-to-pdf'], status:A, processing:c, dataStorage:n },
  { name:'PDF → PNG', slug:'pdf-to-png', category:'PDF', description:'Convert PDF pages to lossless PNG images.', keywords:['pdf to png','pdf to image png'], icon:'ArrowRight', formats:{in:['PDF'],out:['PNG']}, related:['pdf-to-jpg','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'PDF → Text', slug:'pdf-to-text', category:'PDF', description:'Extract all text content from a PDF document.', keywords:['pdf to text','extract text pdf','pdf text extractor'], icon:'FileText', formats:{in:['PDF'],out:['TXT']}, related:['pdf-metadata-viewer','word-counter'], status:A, processing:c, dataStorage:n },
  { name:'JPG → PDF', slug:'jpg-to-pdf', category:'PDF', description:'Convert one or more JPG images into a PDF document.', keywords:['jpg to pdf','image to pdf','photos to pdf'], icon:'ArrowRight', formats:{in:['JPG'],out:['PDF']}, related:['png-to-pdf','image-to-pdf','pdf-compressor'], status:A, processing:c, dataStorage:n },
  { name:'PNG → PDF', slug:'png-to-pdf', category:'PDF', description:'Convert PNG images to a PDF document.', keywords:['png to pdf','convert png pdf'], icon:'ArrowRight', formats:{in:['PNG'],out:['PDF']}, related:['jpg-to-pdf','image-to-pdf'], status:A, processing:c, dataStorage:n },
  { name:'Image → PDF', slug:'image-to-pdf', category:'PDF', description:'Convert any image format to a PDF document.', keywords:['image to pdf','photo to pdf','picture to pdf'], icon:'ImagePlus', formats:{in:['JPG','PNG','WebP'],out:['PDF']}, related:['jpg-to-pdf','pdf-compressor'], status:A, processing:c, dataStorage:n },
  { name:'PDF Metadata Viewer', slug:'pdf-metadata-viewer', category:'PDF', description:'View author, title, creation date and other PDF metadata.', keywords:['pdf metadata','pdf info','pdf properties'], icon:'Info', formats:{in:['PDF']}, related:['pdf-metadata-editor','image-metadata-viewer'], status:A, processing:c, dataStorage:n },
  { name:'PDF Watermark', slug:'pdf-watermark', category:'PDF', description:'Add text or image watermarks to PDF pages.', keywords:['pdf watermark','add watermark pdf','stamp pdf'], icon:'Stamp', formats:{in:['PDF'],out:['PDF']}, related:['pdf-password','image-watermark'], status:A, processing:c, dataStorage:n },
  { name:'PDF Password Protect', slug:'pdf-password', category:'PDF', description:'Encrypt and password-protect PDF files.', keywords:['pdf password','encrypt pdf','protect pdf','lock pdf'], icon:'Lock', formats:{in:['PDF'],out:['PDF']}, related:['pdf-unlock','pdf-compressor'], status:A, processing:c, dataStorage:n },
  { name:'PDF Unlock', slug:'pdf-unlock', category:'PDF', description:'Remove password protection from PDFs you own.', keywords:['unlock pdf','remove pdf password','decrypt pdf'], icon:'Unlock', formats:{in:['PDF'],out:['PDF']}, related:['pdf-password','pdf-compressor'], status:A, processing:c, dataStorage:n },

  // ── Developer ────────────────────────────────────────────────────────────
  { name:'JSON Formatter', slug:'json-formatter', category:'Developer', description:'Format, beautify, and validate JSON with syntax highlighting.', longDescription:'Format messy JSON into readable, indented output with syntax highlighting. Also validates JSON and shows errors with line numbers. Minify mode available.', keywords:['json formatter','format json','json beautifier','json validator','pretty json','json lint'], icon:'Braces', formats:{in:['JSON'],out:['JSON']}, related:['json-validator','json-minifier','csv-to-json','json-to-xml'], status:A, processing:c, dataStorage:n },
  { name:'JSON Validator', slug:'json-validator', category:'Developer', description:'Validate JSON syntax and show detailed error messages.', keywords:['validate json','json lint','json check','json syntax'], icon:'CheckCircle', formats:{in:['JSON']}, related:['json-formatter','json-minifier'], status:S, processing:c, dataStorage:n },
  { name:'JSON Minifier', slug:'json-minifier', category:'Developer', description:'Minify JSON by removing all whitespace and formatting.', keywords:['minify json','compress json','json minifier','small json'], icon:'Minimize2', formats:{in:['JSON'],out:['JSON']}, related:['json-formatter','json-validator'], status:S, processing:c, dataStorage:n },
  { name:'JSON → CSV', slug:'json-to-csv', category:'Developer', description:'Convert JSON arrays to CSV format for spreadsheets.', keywords:['json to csv','export csv json','json csv converter'], icon:'ArrowRight', formats:{in:['JSON'],out:['CSV']}, related:['csv-to-json','json-formatter'], status:S, processing:c, dataStorage:n },
  { name:'CSV → JSON', slug:'csv-to-json', category:'Data', description:'Convert CSV files to JSON format with column mapping.', longDescription:'Parse CSV files and convert them to structured JSON. Handles headers, custom delimiters, and downloads the result.', keywords:['csv to json','convert csv json','csv json converter','parse csv'], icon:'ArrowRight', formats:{in:['CSV'],out:['JSON']}, related:['json-to-csv','json-formatter','csv-cleaner'], status:A, processing:c, dataStorage:n },
  { name:'JSON → XML', slug:'json-to-xml', category:'Developer', description:'Convert JSON to XML format.', keywords:['json to xml','convert xml json'], icon:'ArrowRight', formats:{in:['JSON'],out:['XML']}, related:['xml-to-json','json-formatter'], status:S, processing:c, dataStorage:n },
  { name:'XML → JSON', slug:'xml-to-json', category:'Developer', description:'Convert XML to clean JSON format.', keywords:['xml to json','parse xml json','convert xml'], icon:'ArrowRight', formats:{in:['XML'],out:['JSON']}, related:['json-to-xml','json-formatter'], status:S, processing:c, dataStorage:n },
  { name:'HTML Formatter', slug:'html-formatter', category:'Developer', description:'Beautify and format HTML code with proper indentation.', keywords:['format html','html beautifier','html formatter','pretty html'], icon:'FileCode', related:['css-formatter','html-minifier'], status:S, processing:c, dataStorage:n },
  { name:'CSS Formatter', slug:'css-formatter', category:'Developer', description:'Format and beautify CSS code.', keywords:['format css','css beautifier','css formatter','pretty css'], icon:'FileCode2', related:['html-formatter','css-minifier'], status:S, processing:c, dataStorage:n },
  { name:'JS Formatter', slug:'js-formatter', category:'Developer', description:'Format and prettify JavaScript code.', keywords:['format javascript','js beautifier','prettier js'], icon:'Code', related:['css-formatter','html-formatter'], status:S, processing:c, dataStorage:n },
  { name:'HTML Minifier', slug:'html-minifier', category:'Developer', description:'Minify HTML by removing whitespace and comments.', keywords:['minify html','compress html','html minifier'], icon:'Minimize2', related:['html-formatter','css-minifier'], status:S, processing:c, dataStorage:n },
  { name:'CSS Minifier', slug:'css-minifier', category:'Developer', description:'Minify CSS by removing whitespace and comments.', keywords:['minify css','compress css','css minifier'], icon:'Minimize2', related:['css-formatter','html-minifier'], status:S, processing:c, dataStorage:n },
  { name:'SQL Formatter', slug:'sql-formatter', category:'Developer', description:'Format SQL queries with proper indentation and keywords.', keywords:['format sql','sql beautifier','sql formatter','pretty sql'], icon:'Database', related:['json-formatter','html-formatter'], status:S, processing:c, dataStorage:n },
  { name:'Markdown → HTML', slug:'markdown-to-html', category:'Developer', description:'Convert Markdown text to HTML with live preview.', keywords:['markdown to html','md to html','convert markdown'], icon:'ArrowRight', formats:{in:['MD'],out:['HTML']}, related:['html-formatter','word-counter'], status:S, processing:c, dataStorage:n },
  { name:'Regex Tester', slug:'regex-tester', category:'Developer', description:'Test regular expressions with live match highlighting.', keywords:['regex tester','regular expression','regex checker','test regex'], icon:'Regex', related:['text-diff','find-replace'], status:S, processing:c, dataStorage:n },
  { name:'UUID Generator', slug:'uuid-generator', category:'Developer', description:'Generate UUID v4 identifiers in bulk.', keywords:['uuid generator','generate uuid','guid generator','unique id'], icon:'Hash', related:['password-generator','timestamp-generator'], status:S, processing:c, dataStorage:n },
  { name:'Timestamp Converter', slug:'timestamp-converter', category:'Developer', description:'Convert Unix timestamps to readable dates and vice versa.', keywords:['unix timestamp','convert timestamp','epoch converter','date to timestamp'], icon:'Clock', related:['date-difference','date-calculator'], status:S, processing:c, dataStorage:n },
  { name:'Hash Generator', slug:'hash-generator', category:'Developer', description:'Generate MD5, SHA-1, SHA-256 and SHA-512 hashes from text.', keywords:['hash generator','md5 hash','sha256','sha512','generate hash'], icon:'Shield', related:['md5-hash','sha256-hash','base64-encoder'], status:S, processing:c, dataStorage:n },
  { name:'JWT Decoder', slug:'jwt-decoder', category:'Developer', description:'Decode JWT tokens and inspect header, payload, and signature.', keywords:['jwt decoder','decode jwt','json web token','jwt inspector'], icon:'Key', related:['base64-decoder','json-formatter'], status:S, processing:c, dataStorage:n },
  { name:'Text Diff', slug:'text-diff', category:'Developer', description:'Compare two texts and highlight differences side by side.', keywords:['text diff','compare text','diff tool','text compare'], icon:'GitCompare', related:['json-formatter','find-replace'], status:S, processing:c, dataStorage:n },
  { name:'Cron Expression Generator', slug:'cron-generator', category:'Developer', description:'Build and explain cron expressions with a visual interface.', keywords:['cron expression','cron generator','cron builder','cron syntax'], icon:'Timer', related:['timestamp-converter','uuid-generator'], status:S, processing:c, dataStorage:n },

  // ── Data ────────────────────────────────────────────────────────────────
  { name:'JSON → CSV', slug:'json-to-csv-data', category:'Data', description:'Convert JSON data arrays to CSV format.', keywords:['json to csv','export json csv'], icon:'ArrowRight', formats:{in:['JSON'],out:['CSV']}, related:['csv-to-json','json-formatter'], status:S, processing:c, dataStorage:n },
  { name:'CSV Cleaner', slug:'csv-cleaner', category:'Data', description:'Clean CSV files by removing empty rows, fixing delimiters, and trimming whitespace.', keywords:['clean csv','csv fixer','remove empty rows csv'], icon:'Eraser', formats:{in:['CSV'],out:['CSV']}, related:['csv-to-json','csv-deduplicator'], status:S, processing:c, dataStorage:n },
  { name:'CSV Deduplicator', slug:'csv-deduplicator', category:'Data', description:'Remove duplicate rows from CSV files based on selected columns.', keywords:['deduplicate csv','remove duplicates csv','unique rows csv'], icon:'Filter', formats:{in:['CSV'],out:['CSV']}, related:['csv-cleaner','csv-sorter'], status:S, processing:c, dataStorage:n },
  { name:'CSV Column Extractor', slug:'csv-column-extractor', category:'Data', description:'Extract specific columns from a CSV file.', keywords:['extract csv columns','select columns csv','csv column picker'], icon:'Columns', formats:{in:['CSV'],out:['CSV']}, related:['csv-cleaner','csv-to-json'], status:S, processing:c, dataStorage:n },
  { name:'CSV Sorter', slug:'csv-sorter', category:'Data', description:'Sort CSV rows by any column, ascending or descending.', keywords:['sort csv','order csv','csv sort rows'], icon:'ArrowUpDown', formats:{in:['CSV'],out:['CSV']}, related:['csv-cleaner','csv-deduplicator'], status:S, processing:c, dataStorage:n },
  { name:'YAML → JSON', slug:'yaml-to-json', category:'Data', description:'Convert YAML files to JSON format.', keywords:['yaml to json','convert yaml json'], icon:'ArrowRight', formats:{in:['YAML'],out:['JSON']}, related:['json-to-xml','json-formatter'], status:S, processing:c, dataStorage:n },
  { name:'JSON → YAML', slug:'json-to-yaml', category:'Data', description:'Convert JSON to YAML format.', keywords:['json to yaml','convert yaml'], icon:'ArrowRight', formats:{in:['JSON'],out:['YAML']}, related:['yaml-to-json','json-formatter'], status:S, processing:c, dataStorage:n },

  // ── Text ─────────────────────────────────────────────────────────────────
  { name:'Word Counter', slug:'word-counter', category:'Text', description:'Count words, characters, sentences, and paragraphs in real time.', longDescription:'Instantly count words, characters (with/without spaces), sentences, paragraphs, and estimate reading time. Works on any text you paste or type.', keywords:['word counter','count words','word count','text counter','words in text'], icon:'AlignLeft', related:['character-counter','reading-time','lorem-ipsum'], status:A, processing:c, dataStorage:n },
  { name:'Character Counter', slug:'character-counter', category:'Text', description:'Count characters with and without spaces, and byte length.', longDescription:'Detailed character analysis: total characters, characters without spaces, byte count, and Unicode code point breakdown.', keywords:['character counter','char count','count characters','text length','character count'], icon:'Type', related:['word-counter','reading-time'], status:A, processing:c, dataStorage:n },
  { name:'Reading Time', slug:'reading-time', category:'Text', description:'Estimate how long it takes to read a piece of text.', longDescription:'Estimates reading time based on average reading speeds (slow/average/fast). Shows word count and reading time in minutes.', keywords:['reading time','read time calculator','how long to read','minutes to read'], icon:'Clock', related:['word-counter','character-counter'], status:A, processing:c, dataStorage:n },
  { name:'Case Converter', slug:'case-converter', category:'Text', description:'Convert text between UPPERCASE, lowercase, Title Case, and camelCase.', keywords:['case converter','uppercase','lowercase','title case','camel case'], icon:'CaseSensitive', related:['text-cleaner','slug-generator'], status:S, processing:c, dataStorage:n },
  { name:'Remove Duplicate Lines', slug:'remove-duplicate-lines', category:'Text', description:'Remove duplicate lines from any block of text.', keywords:['remove duplicate lines','unique lines','deduplicate text'], icon:'ListFilter', related:['sort-lines','text-cleaner'], status:S, processing:c, dataStorage:n },
  { name:'Sort Lines', slug:'sort-lines', category:'Text', description:'Sort lines of text alphabetically or reverse alphabetically.', keywords:['sort lines','sort text','alphabetical sort'], icon:'ArrowUpDown', related:['remove-duplicate-lines','reverse-text'], status:S, processing:c, dataStorage:n },
  { name:'Reverse Text', slug:'reverse-text', category:'Text', description:'Reverse the characters or lines of any text.', keywords:['reverse text','flip text','mirror text'], icon:'ArrowLeftRight', related:['sort-lines','text-cleaner'], status:S, processing:c, dataStorage:n },
  { name:'Find & Replace', slug:'find-replace', category:'Text', description:'Find and replace text with regex support.', keywords:['find replace','text replace','regex replace','bulk replace'], icon:'SearchCheck', related:['text-diff','regex-tester'], status:S, processing:c, dataStorage:n },
  { name:'Text Cleaner', slug:'text-cleaner', category:'Text', description:'Remove extra spaces, special characters, and invisible characters.', keywords:['clean text','remove spaces','strip text','text sanitizer'], icon:'Eraser', related:['whitespace-remover','case-converter'], status:S, processing:c, dataStorage:n },
  { name:'Whitespace Remover', slug:'whitespace-remover', category:'Text', description:'Remove leading, trailing, and extra whitespace from text.', keywords:['remove whitespace','trim text','extra spaces'], icon:'RemoveFormatting', related:['text-cleaner','remove-duplicate-lines'], status:S, processing:c, dataStorage:n },
  { name:'Slug Generator', slug:'slug-generator', category:'Text', description:'Convert text to URL-friendly slugs.', keywords:['slug generator','url slug','text to slug','seo url'], icon:'Link', related:['case-converter','text-cleaner'], status:S, processing:c, dataStorage:n },
  { name:'Lorem Ipsum Generator', slug:'lorem-ipsum', category:'Text', description:'Generate Lorem Ipsum placeholder text.', keywords:['lorem ipsum','placeholder text','dummy text','filler text'], icon:'Text', related:['word-counter','character-counter'], status:S, processing:c, dataStorage:n },

  // ── Calculators ──────────────────────────────────────────────────────────
  { name:'Percentage Calculator', slug:'percentage-calculator', category:'Calculators', description:'Calculate percentages, percentage change, and percentage of a value.', keywords:['percentage calculator','percent calculator','calculate percentage'], icon:'Percent', related:['discount-calculator','gst-calculator'], status:S, processing:c, dataStorage:n },
  { name:'Age Calculator', slug:'age-calculator', category:'Calculators', description:'Calculate exact age in years, months, and days from a date of birth.', keywords:['age calculator','calculate age','how old am i','birthday calculator'], icon:'Cake', related:['date-difference','date-calculator'], status:S, processing:c, dataStorage:n },
  { name:'BMI Calculator', slug:'bmi-calculator', category:'Calculators', description:'Calculate Body Mass Index from height and weight.', keywords:['bmi calculator','body mass index','bmi formula'], icon:'Activity', related:['percentage-calculator'], status:S, processing:c, dataStorage:n },
  { name:'EMI Calculator', slug:'emi-calculator', category:'Calculators', description:'Calculate monthly EMI for loans with amortization schedule.', keywords:['emi calculator','loan emi','equated monthly installment','loan calculator'], icon:'Banknote', related:['loan-calculator','sip-calculator','mortgage-calculator'], status:S, processing:c, dataStorage:n },
  { name:'Loan Calculator', slug:'loan-calculator', category:'Calculators', description:'Calculate loan payments, total interest, and amortization.', keywords:['loan calculator','loan interest','monthly payment','personal loan'], icon:'Wallet', related:['emi-calculator','compound-interest'], status:S, processing:c, dataStorage:n },
  { name:'Compound Interest Calculator', slug:'compound-interest', category:'Calculators', description:'Calculate compound interest over time with different compounding frequencies.', keywords:['compound interest','ci calculator','investment returns'], icon:'TrendingUp', related:['simple-interest','sip-calculator','fd-calculator'], status:S, processing:c, dataStorage:n },
  { name:'Simple Interest Calculator', slug:'simple-interest', category:'Calculators', description:'Calculate simple interest on a principal amount.', keywords:['simple interest','si calculator','interest rate'], icon:'TrendingUp', related:['compound-interest','loan-calculator'], status:S, processing:c, dataStorage:n },
  { name:'GST Calculator', slug:'gst-calculator', category:'Calculators', description:'Calculate GST (5%, 12%, 18%, 28%) and get inclusive/exclusive prices.', keywords:['gst calculator','goods services tax','tax calculator','vat calculator'], icon:'Receipt', related:['percentage-calculator','discount-calculator'], status:S, processing:c, dataStorage:n },
  { name:'Discount Calculator', slug:'discount-calculator', category:'Calculators', description:'Calculate the final price after a percentage discount.', keywords:['discount calculator','sale price','percent off','coupon calculator'], icon:'Tag', related:['percentage-calculator','gst-calculator'], status:S, processing:c, dataStorage:n },
  { name:'SIP Calculator', slug:'sip-calculator', category:'Calculators', description:'Calculate SIP returns, maturity amount, and wealth gain for mutual fund investments.', longDescription:'Calculate Systematic Investment Plan (SIP) maturity value, total investment, and estimated returns based on monthly investment, expected annual return, and investment tenure.', keywords:['sip calculator','systematic investment plan','mutual fund sip','sip returns','monthly investment'], icon:'PiggyBank', related:['compound-interest','fd-calculator','emi-calculator'], status:A, processing:c, dataStorage:n },
  { name:'FD Calculator', slug:'fd-calculator', category:'Calculators', description:'Calculate Fixed Deposit maturity amount and interest earned.', keywords:['fd calculator','fixed deposit','bank fd','fd interest'], icon:'Landmark', related:['sip-calculator','compound-interest'], status:S, processing:c, dataStorage:n },
  { name:'Date Difference Calculator', slug:'date-difference', category:'Calculators', description:'Calculate the difference between two dates in days, months, and years.', keywords:['date difference','days between dates','calculate days','date calculator'], icon:'CalendarDays', related:['age-calculator','date-calculator','timestamp-converter'], status:S, processing:c, dataStorage:n },
  { name:'Unit Converter', slug:'unit-converter', category:'Calculators', description:'Convert between length, weight, temperature, area, volume, and more.', keywords:['unit converter','convert units','length converter','weight converter','temperature converter'], icon:'Ruler', related:['percentage-calculator'], status:S, processing:c, dataStorage:n },

  // ── Design ───────────────────────────────────────────────────────────────
  { name:'Color Picker', slug:'color-picker', category:'Design', description:'Pick colours and get HEX, RGB, HSL, and CSS values.', keywords:['color picker','colour picker','hex color','rgb color','pick color'], icon:'Pipette', related:['hex-to-rgb','color-palette','css-gradient'], status:S, processing:c, dataStorage:n },
  { name:'HEX → RGB', slug:'hex-to-rgb', category:'Design', description:'Convert HEX colour codes to RGB values.', keywords:['hex to rgb','hex color converter','rgb hex'], icon:'ArrowRight', related:['rgb-to-hex','hsl-converter','color-picker'], status:S, processing:c, dataStorage:n },
  { name:'RGB → HEX', slug:'rgb-to-hex', category:'Design', description:'Convert RGB values to HEX colour codes.', keywords:['rgb to hex','color hex','hex code'], icon:'ArrowRight', related:['hex-to-rgb','color-picker'], status:S, processing:c, dataStorage:n },
  { name:'HSL Converter', slug:'hsl-converter', category:'Design', description:'Convert between HSL, RGB, and HEX colour formats.', keywords:['hsl converter','hsl to rgb','hsl to hex'], icon:'Rainbow', related:['hex-to-rgb','rgb-to-hex'], status:S, processing:c, dataStorage:n },
  { name:'Color Palette Generator', slug:'color-palette', category:'Design', description:'Generate beautiful colour palettes from a base colour.', keywords:['color palette','colour palette generator','palette generator'], icon:'Palette', related:['color-picker','css-gradient'], status:S, processing:c, dataStorage:n },
  { name:'CSS Gradient Generator', slug:'css-gradient', category:'Design', description:'Build linear and radial CSS gradients with a live preview.', keywords:['css gradient','gradient generator','linear gradient','radial gradient'], icon:'Layers', related:['css-shadow','color-palette'], status:S, processing:c, dataStorage:n },
  { name:'CSS Shadow Generator', slug:'css-shadow', category:'Design', description:'Generate box-shadow CSS with visual controls.', keywords:['css shadow','box shadow generator','drop shadow css'], icon:'Square', related:['css-gradient','glassmorphism'], status:S, processing:c, dataStorage:n },
  { name:'Glassmorphism Generator', slug:'glassmorphism', category:'Design', description:'Generate glassmorphism CSS effects with backdrop blur.', keywords:['glassmorphism','glass effect css','backdrop blur','glass morphism'], icon:'Layers', related:['css-shadow','neumorphism'], status:S, processing:c, dataStorage:n },
  { name:'Border Radius Generator', slug:'border-radius-generator', category:'Design', description:'Visually generate complex border-radius CSS values.', keywords:['border radius','css border radius','rounded corners','css radius'], icon:'Box', related:['css-shadow','css-gradient'], status:S, processing:c, dataStorage:n },
  { name:'Favicon Generator', slug:'favicon-generator', category:'Design', description:'Generate favicon files in all required sizes from any image or text.', longDescription:'Upload an image or type text/emoji to generate favicon.ico, PNG favicons (16×16, 32×32, 48×48, 192×192, 512×512), and an apple-touch-icon — all sizes needed for modern websites.', keywords:['favicon generator','create favicon','website icon','ico generator','site icon'], icon:'Smile', related:['svg-cleaner','image-compressor'], status:A, processing:c, dataStorage:n },
  { name:'SVG Blob Generator', slug:'svg-blob', category:'Design', description:'Generate organic SVG blob shapes for backgrounds and decorations.', keywords:['svg blob','blob generator','organic shape','blob shape'], icon:'Shapes', related:['svg-wave','css-gradient'], status:S, processing:c, dataStorage:n },
  { name:'SVG Wave Generator', slug:'svg-wave', category:'Design', description:'Generate smooth SVG wave dividers for website sections.', keywords:['svg wave','wave generator','section divider svg'], icon:'Waves', related:['svg-blob','css-gradient'], status:S, processing:c, dataStorage:n },

  // ── Audio ────────────────────────────────────────────────────────────────
  { name:'MP3 Trimmer', slug:'mp3-trimmer', category:'Audio', description:'Trim MP3 files to select start and end points.', keywords:['mp3 trimmer','trim audio','cut mp3','audio cutter'], icon:'Scissors', formats:{in:['MP3'],out:['MP3']}, related:['audio-trimmer','audio-merger'], status:S, processing:c, dataStorage:n },
  { name:'Audio Trimmer', slug:'audio-trimmer', category:'Audio', description:'Trim any audio file with a waveform editor.', keywords:['audio trimmer','trim audio','cut audio','audio cutter'], icon:'Scissors', formats:{in:['MP3','WAV','OGG'],out:['MP3','WAV']}, related:['mp3-trimmer','audio-merger'], status:S, processing:c, dataStorage:n },
  { name:'Audio Merger', slug:'audio-merger', category:'Audio', description:'Merge multiple audio files into one.', keywords:['audio merger','combine audio','join audio files','merge mp3'], icon:'Merge', formats:{in:['MP3','WAV'],out:['MP3','WAV']}, related:['audio-trimmer','mp3-trimmer'], status:S, processing:c, dataStorage:n },
  { name:'MP3 → WAV', slug:'mp3-to-wav', category:'Audio', description:'Convert MP3 audio files to WAV format.', keywords:['mp3 to wav','convert mp3 wav','audio converter'], icon:'ArrowRight', formats:{in:['MP3'],out:['WAV']}, related:['wav-to-mp3','audio-trimmer'], status:S, processing:c, dataStorage:n },
  { name:'WAV → MP3', slug:'wav-to-mp3', category:'Audio', description:'Convert WAV audio files to compressed MP3 format.', keywords:['wav to mp3','convert wav mp3'], icon:'ArrowRight', formats:{in:['WAV'],out:['MP3']}, related:['mp3-to-wav','audio-trimmer'], status:S, processing:c, dataStorage:n },
  { name:'Audio Volume Changer', slug:'audio-volume', category:'Audio', description:'Increase or decrease the volume of an audio file.', keywords:['audio volume','boost volume','increase volume mp3'], icon:'Volume2', formats:{in:['MP3','WAV'],out:['MP3','WAV']}, related:['audio-trimmer','mp3-trimmer'], status:S, processing:c, dataStorage:n },
  { name:'Audio Metadata Remover', slug:'audio-metadata-remover', category:'Audio', description:'Remove ID3 tags and metadata from audio files.', keywords:['remove audio metadata','strip id3 tags','audio privacy'], icon:'EyeOff', formats:{in:['MP3'],out:['MP3']}, related:['image-metadata-remover','audio-trimmer'], status:S, processing:c, dataStorage:n },

  // ── Generators ───────────────────────────────────────────────────────────
  { name:'QR Code Generator', slug:'qr-generator', category:'Generators', description:'Generate QR codes for URLs, text, email, and more. Download as PNG or SVG.', keywords:['qr code generator','create qr code','qr code maker','qr generator'], icon:'QrCode', related:['barcode-generator','url-encoder'], status:S, processing:c, dataStorage:n },
  { name:'Barcode Generator', slug:'barcode-generator', category:'Generators', description:'Generate barcodes in Code128, EAN-13, and other formats.', keywords:['barcode generator','create barcode','ean barcode','code128'], icon:'BarChart2', related:['qr-generator'], status:S, processing:c, dataStorage:n },
  { name:'Password Generator', slug:'password-generator', category:'Generators', description:'Generate strong, random passwords with custom rules.', keywords:['password generator','strong password','random password','secure password'], icon:'KeyRound', related:['password-strength','uuid-generator'], status:S, processing:c, dataStorage:n },
  { name:'Random Number Generator', slug:'random-number', category:'Generators', description:'Generate random numbers within any range.', keywords:['random number','number generator','dice roller','random integer'], icon:'Dice5', related:['uuid-generator','password-generator'], status:S, processing:c, dataStorage:n },
  { name:'Placeholder Image Generator', slug:'placeholder-image', category:'Generators', description:'Generate placeholder images with custom size, colour, and text.', keywords:['placeholder image','dummy image','test image','placeholder.com'], icon:'ImagePlus', related:['favicon-generator','image-compressor'], status:S, processing:c, dataStorage:n },
  { name:'Timestamp Generator', slug:'timestamp-generator', category:'Generators', description:'Generate current or custom Unix timestamps.', keywords:['timestamp generator','unix timestamp','epoch now','generate timestamp'], icon:'Clock', related:['timestamp-converter','date-difference'], status:S, processing:c, dataStorage:n },

  // ── Security ────────────────────────────────────────────────────────────
  { name:'Base64 Encoder', slug:'base64-encoder', category:'Security', description:'Encode text or files to Base64 and decode Base64 back to text.', longDescription:'Encode text to Base64 or decode Base64 back to readable text. Also supports encoding files to Base64 data URLs. All processing happens locally in your browser.', keywords:['base64 encoder','base64 decoder','encode base64','decode base64','base64 converter'], icon:'Binary', related:['base64-decoder','url-encoder','hash-generator'], status:A, processing:c, dataStorage:n },
  { name:'Base64 Decoder', slug:'base64-decoder', category:'Security', description:'Decode Base64 encoded strings back to plain text or files.', keywords:['base64 decoder','decode base64','base64 to text'], icon:'Binary', related:['base64-encoder','url-decoder'], status:S, processing:c, dataStorage:n },
  { name:'URL Encoder', slug:'url-encoder', category:'Security', description:'Encode URLs and query strings using percent-encoding.', keywords:['url encoder','percent encode','urlencode','encode url'], icon:'Link', related:['url-decoder','base64-encoder'], status:S, processing:c, dataStorage:n },
  { name:'URL Decoder', slug:'url-decoder', category:'Security', description:'Decode percent-encoded URLs back to readable text.', keywords:['url decoder','decode url','urldecode','percent decode'], icon:'Link', related:['url-encoder','base64-decoder'], status:S, processing:c, dataStorage:n },
  { name:'MD5 Hash Generator', slug:'md5-hash', category:'Security', description:'Generate MD5 hashes from any text input.', keywords:['md5 hash','md5 generator','checksum md5'], icon:'Shield', related:['sha256-hash','hash-generator'], status:S, processing:c, dataStorage:n },
  { name:'SHA-256 Hash', slug:'sha256-hash', category:'Security', description:'Generate SHA-256 cryptographic hashes from text.', keywords:['sha256 hash','sha-256','sha256 generator','crypto hash'], icon:'ShieldCheck', related:['md5-hash','sha512-hash','hash-generator'], status:S, processing:c, dataStorage:n },
  { name:'SHA-512 Hash', slug:'sha512-hash', category:'Security', description:'Generate SHA-512 hashes from any text input.', keywords:['sha512 hash','sha-512','sha512 generator'], icon:'ShieldCheck', related:['sha256-hash','md5-hash'], status:S, processing:c, dataStorage:n },
  { name:'JWT Decoder', slug:'jwt-decoder-sec', category:'Security', description:'Decode and inspect JWT tokens — header, payload, and signature.', keywords:['jwt decoder','decode jwt token','json web token','jwt inspector'], icon:'Key', related:['base64-decoder','json-formatter'], status:S, processing:c, dataStorage:n },
  { name:'Password Strength Checker', slug:'password-strength', category:'Security', description:'Check the strength of any password with entropy analysis.', keywords:['password strength','password checker','strong password test','entropy'], icon:'ShieldAlert', related:['password-generator'], status:S, processing:c, dataStorage:n },

  // ── Files ────────────────────────────────────────────────────────────────
  { name:'File Hash Generator', slug:'file-hash', category:'Files', description:'Generate MD5, SHA-256, and SHA-512 checksums for any file.', keywords:['file hash','file checksum','md5 file','sha256 file','verify file'], icon:'FileCheck', related:['sha256-hash','file-metadata'], status:S, processing:c, dataStorage:n },
  { name:'File Metadata Viewer', slug:'file-metadata', category:'Files', description:'View file name, size, type, and last-modified date.', keywords:['file metadata','file info','file size','file type'], icon:'Info', related:['file-hash','mime-checker'], status:S, processing:c, dataStorage:n },
  { name:'MIME Type Checker', slug:'mime-checker', category:'Files', description:'Detect the MIME type of any file by content inspection.', keywords:['mime type','file type checker','detect mime','file format'], icon:'FileSearch', related:['file-metadata','file-hash'], status:S, processing:c, dataStorage:n },
  { name:'ZIP Creator', slug:'zip-creator', category:'Files', description:'Create ZIP archives from multiple files in your browser.', keywords:['zip creator','create zip','make zip','compress files'], icon:'Archive', related:['file-hash','file-metadata'], status:S, processing:c, dataStorage:n },
];

// Remove any duplicate slugs (CSV-to-JSON appears in both Developer and Data)
const seen = new Set<string>();
export const TOOLS_DEDUPED = TOOLS.filter(t => {
  if (seen.has(t.slug)) return false;
  seen.add(t.slug);
  return true;
});

// Re-export as TOOLS for backward compat
export { TOOLS_DEDUPED as TOOLS_ALL };

export const TOOL_MAP: Record<string, Tool> = Object.fromEntries(
  TOOLS_DEDUPED.map(t => [t.slug, t])
);

export const CATEGORIES: Category[] = [
  'Images','PDF','Developer','Data','Text','Calculators','Design','Audio','Generators','Security','Files'
];

export const CATEGORY_ICONS: Record<Category, string> = {
  Images:      'Image',
  PDF:         'FileText',
  Developer:   'Code2',
  Data:        'Table',
  Text:        'AlignLeft',
  Calculators: 'Calculator',
  Design:      'Palette',
  Audio:       'Music',
  Generators:  'Wand2',
  Security:    'Shield',
  Files:       'Folder',
};

export const CATEGORY_DESCRIPTIONS: Record<Category, string> = {
  Images:      'Compress, convert, resize, and edit images',
  PDF:         'Merge, split, compress, and convert PDF files',
  Developer:   'Format, validate, and transform code and data',
  Data:        'Convert, clean, and transform data files',
  Text:        'Count, format, and manipulate text',
  Calculators: 'Financial, math, and everyday calculators',
  Design:      'Generate colors, gradients, shadows, and assets',
  Audio:       'Trim, convert, and process audio files',
  Generators:  'Generate QR codes, passwords, UUIDs, and more',
  Security:    'Encode, hash, and analyze data securely',
  Files:       'Inspect, hash, and manage file metadata',
};

export function getToolsByCategory(cat: Category): Tool[] {
  return TOOLS_DEDUPED.filter(t => t.category === cat);
}

export function getRelatedTools(slug: string, limit = 4): Tool[] {
  const tool = TOOL_MAP[slug];
  if (!tool) return [];
  return tool.related
    .map(s => TOOL_MAP[s])
    .filter((t): t is Tool => !!t)
    .slice(0, limit);
}

export function getPopularTools(limit = 9): Tool[] {
  const active = TOOLS_DEDUPED.filter(t => t.status === 'active');
  const stubs  = TOOLS_DEDUPED.filter(t => t.status === 'stub').slice(0, limit - active.length);
  return [...active, ...stubs].slice(0, limit);
}
